askdjango/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^weblog/', include('blog.urls', namespace='blog')),
    url(r'^dojo/', include('dojo.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.post_delete, name='post_delete'),
    url(r'^new/$', views.post_new, name='post_new'),
]

blog/models.py
import os
import uuid
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse


def min_length_3(value):
    if len(value) < 3:
        raise ValidationError('3글자 이상 입력해주세요.')


def random_upload_to(instance, filename):
    ext = os.path.splitext(filename)[-1].lower()  # .jpg
    filename = uuid.uuid4().hex + ext
    filepath = os.path.join(filename[:3], filename[3:6], filename[6:9], filename[9:])
    return filepath


class Post(models.Model):
    author = models.CharField(max_length=20, help_text='글쓴이 이름을 입력해주세요.')
    title = models.CharField(max_length=100,
            validators=[min_length_3],
            help_text='제목은 간결하게!!')
    content = models.TextField()
    photo = models.ImageField(upload_to=random_upload_to)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def get_absolute_url(self):
        # return '/weblog/{}/'.format(self.id)
        return reverse('blog:post_detail', args=[self.id])

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

blog/views.py
import datetime
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import redirect, render
from .models import Post
from .forms import PostForm


def post_list(request):
    qs = Post.objects.all()

    query = request.GET.get('query', '')
    if query:
        condition = Q(title__icontains=query) | Q(content__icontains=query)
        qs = qs.filter(condition)

    date_list = []
    for i in range(365):
        date = datetime.datetime(2017, 1, 1) + datetime.timedelta(days=i)
        date_list.append(date)

    return render(request, 'blog/post_list.html', {
        'post_list': qs,
        'query': query,
        'date_list': date_list,
    })


def post_detail(request, pk):
    # pk = "100"  # /blog/100/
    # post = Post.objects.get(id=pk)
    post = Post.objects.get(pk=pk)
    return render(request, 'blog/post_detail.html', {
        'post': post,
    })


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            return redirect(post)
    else:
    # if request.method == 'GET':
        form = PostForm()

    return render(request, 'blog/post_form.html', {
        'form': form,
    })

# from django.views.generic import CreateView
# post_new = CreateView.as_view(model=Post, form_class=PostForm, success_url='/weblog/')
# post_new = CreateView.as_view(model=Post, form_class=PostForm)  # get_absolute_url을 활용


@login_required
def post_edit(request, pk):
    post = Post.objects.get(pk=pk)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            return redirect(post)
    else:
        # if request.method == 'GET':
        form = PostForm(instance=post)

    return render(request, 'blog/post_form.html', {
        'form': form,
    })


def post_delete(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:post_list')
    return render(request, 'blog/post_confirm_delete.html', {
        'post': post,
    })

blog/templates/blog/layout.html
{% extends "layout.html" %}

{% block title %}AskDjango 블로그{% endblock %}

{% block page_title %}AskDjango 블로그{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/layout.html" %}

{% block content %}
    <h3>{{ post.title }}</h3>

    <form action="" method="post">
        {% csrf_token %}
        <div class="alert alert-danger">
            정말 삭제하시겠습니까?
            낙장불입입니다!!
        </div>
        <input type="submit" value="후회없습니다." class="btn btn-danger" />
        <a href="{{ post.get_absolute_url }}" class="btn btn-warning">아니요. 삭제안합니다.</a>
    </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block content %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <h4>{{ post.title }} <small>by {{ post.author }}</small></h4>
        </div>
        <div class="panel-body">
            {% if post.photo %}
            <img src="{{ post.photo.url }}" style="width: 100px;" />
            {% endif %}
            {{ post.content|linebreaks }}
        </div>
        <div class="panel-footer">
            <a href="{% url "blog:post_list" %}" class="btn btn-primary">목록</a>
            <a href="{% url "blog:post_edit" post.id %}" class="btn btn-default">수정</a>
            <a href="{% url "blog:post_delete" post.id %}" class="btn btn-default">삭제</a>
            {# <a href="/weblog/">목록</a> #}
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/layout.html" %}
{% load bootstrap3 %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary btn-block" />
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <p>안녕하세요. 여러분의 파이썬/장고 페이스메이커가 되겠습니다. ;)</p>

    <p>
        <a href="{% url "blog:post_new" %}" class="btn btn-primary pull-right">New Post</a>

        <form action="" method="get">
            <input type="text" name="query" value="{{ query }}" />
            <input type="submit" value="검색" />
        </form>
    </p>

    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>제목</th>
                <th>일시</th>
            </tr>
        </thead>
        <tbody>
            {% for post in post_list %}
            <tr>
                <td>
                    <a href="{{ post.get_absolute_url }}">
                    {# <a href="/weblog/{{ post.pk }}/"> #}
                        {{ post.title }}
                    </a>
                </td>
                <td>
                    {{ post.created_at|timesince }} 전에
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}